server:
    host: 0.0.0.0
    port: 8080
database:
    driver: postgres
    username: dbuser
    password: changeit
    host: postgres
    port: 5432
    name: goat
log:
    debug: true
    file: /app/goat.log
