version: '3.9'

services:
  goat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - internal
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./:/app
  
  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=goat
    networks:
      - internal
    volumes:
      - database:/var/lib/postgresql/data

networks:
  internal:
    external: false
volumes:
  database: {}
